travis:
  secure:
    BINSTAR_TOKEN: LP307tm/v5IiI8wLb6AviCG+f4eEh7cbNVb5XqUpcJfgQuIXg3tU4B/A0WKOxnhA/93pJdoEZxDE9668+YG1N1bc70myb+M5y1IbHKk370jqogI9dirfaG8z6zuYqDE+H368uQHXq+5Sda/o4p1K/ACex4ehH+07P/v02W3vpWXQ+CGSIq/k5EIiODHdbAB1VV7FnBaL1IaCVi9hL/vZc2I2NQhLbi8N3agSyudczxByj+1R8cLi5WvxGnnXv9fiIMQ/bq18raHnEoiRvdeJ+ZO9z1Hs6R/91KLbyAt51orqkZUB4vZbQgBopwmreQ5eMa2pQp8i9puK8DSl5wI+Sv4PluhhWRizgEC8nxG/tnMXM1GBcecTdBZI//zyHjuGte39W5A6cUgoZxgX59XKopZps2jZH5RetVSCTtY4SanJZ9bLnrWIJB3/kMQLGJfoDAw+EQcVVole5k0b2GZNSR5R+rLY2PKnSNPZHMwfEh5z+wGkKwZ0o08x63jtJUcNR/vCyE+KIpOrma2jiJR1F3ppG92oEsYZsc4LiHl9+tpAT1iCuuFrrbmK2PeX9jb0nJkeyqydzUhHXgyvDRJhrLoZJugBkZoeymjH/i34HLaViRsZOErKcyUV0TKDxT0hrfvEg42FUvVvaM1i/5c5p/0nJKqxEWC1ft1jAq2Vftk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
